### ISSUE TITLE
bash $LINES reports 1 after resize

### ISSUE THREAD

**Issue by russau** [princjef/xterm-electron-sample#1]
https://github.com/princjef/xterm-electron-sample/blob/8da1f0f2e4dd183f4ed5c39a2cfabf0b093486da/src/renderer/index.ts#L37

I'm playing around with this code for a project of mine when I notice nano in bash refused to launch after a window resize.  I noticed $LINES reports 1 after a window is resized.  Maybe I should be reporting this in node-pty?  I tried upgrading node-pty to 0.8.0 and I see the same issue.

I see the same issue on Ubuntu and Mac OS.  Let me know if you need any more detail from me.

<img width="966" alt="resize-pty" src="https://user-images.githubusercontent.com/167762/51066147-6d674f00-15bd-11e9-98c8-d424afe4c196.png">

**Comment by russau** [comment]
Do'h I was looking right at it.

https://github.com/princjef/xterm-electron-sample/blob/8da1f0f2e4dd183f4ed5c39a2cfabf0b093486da/src/renderer/index.ts#L39

This should be max not min. 😸

**Comment by princjef** [comment]
Indeed it should! Thanks for the catch and the PR!

**Comment by princjef** [comment]
closed by #2
